name: Python application

on: 
  push:
    branches:
      - master
      - "[0-9]+.[0-9]+.x"
    tags:
      - "*"

  pull_request:
    branches:
      - master
      - "[0-9]+.[0-9]+.x"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        name: ["linting", "ubuntu-py36", "ubuntu-py37", "ubuntu-py38", "macos-py37", "macos-py38"]

        include:
          - name: "linting"
            python: "3.7"
            os: ubuntu-latest
            tox_env: "linting"
            
          - name: "ubuntu-py36"
            python: "3.6"
            os: ubuntu-latest
            tox_env: "py36-xdist"
          - name: "ubuntu-py37"
            python: "3.7"
            os: ubuntu-latest
            tox_env: "py37-xdist"
          - name: "ubuntu-py38"
            python: "3.8"
            os: ubuntu-latest
            tox_env: "py38-xdist"

          - name: "macos-py37"
            python: "3.7"
            os: macos-latest
            tox_env: "py37-xdist"
          - name: "macos-py38"
            python: "3.8"
            os: macos-latest
            tox_env: "py38-xdist"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Test without coverage
      if: "! matrix.use_coverage"
      run: "tox -e ${{ matrix.tox_env }}"

